name: Slack PR Notification
on:
  # use pull_request_target to run on PRs from forks and have access to secrets
  pull_request_target:
    types: [labeled, closed]

env:
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  # channel: "wg-open-source"
  # for testing
  channel: "rc-test"

jobs:
  rfc:
    name: RFC Notification
    runs-on: ubuntu-latest
    # Trigger when labeling a PR with "RFC"
    if: |
      github.event.action == 'labeled' &&
      contains(toJson(github.event.pull_request.labels.*.name), '"RFC"')
    steps: 
    - name: Notify Slack
      uses: slackapi/slack-github-action@v1.25.0
      with:
        # channel-id: "wg-open-source"
        channel-id: ${{ env.channel }}
        slack-message: "${{ github.actor }} posted a RFC: ${{ github.event.pull_request.title }}. URL: ${{ github.event.pull_request.html_url }}"

  meeting-notes:
    name: Meeting Notes Notification
    runs-on: ubuntu-latest
    # Trigger when closing a PR with "meeting notes" label
    if: |
      github.event.action == 'closed' &&
      github.event.pull_request.merged == true &&
      contains(toJson(github.event.pull_request.labels.*.name), '"meeting notes"')
    steps: 
    - name: Notify Slack
      uses: slackapi/slack-github-action@v1.25.0
      with:
        channel-id: ${{ env.channel }}
        slack-message: "${{ github.actor }} posted meeting notes: ${{ github.event.pull_request.title }}. URL: ${{ github.event.pull_request.html_url }}"
